### ISSUE TITLE
Changing rules for PR without opening an Issue

### ISSUE THREAD

**Issue by Student007** [tessel/project#146]
As suggested by @johnnyman727 https://github.com/tessel/t2-cli/pull/640#issuecomment-207446672 I ask for discussion about being allowed to open PRs for **ready to use features.**

The [guidelines](https://github.com/tessel/project/blob/master/CONTRIBUTING.md#pull-requests)  do not cover this need but in practice multiple cases are seen members are doing contributions without opening issues.

Here is a **draft** for changing the guidelines by adding a chapter:
# Ready for use Pull Requests
If you have created a **useful feature** with your fork of parts of the Tessel Project we love to review this directly without require you to open an issue. We do not like to have any barrier like intensive discussions. But be aware it is possible we rework and overwrite your work more or less quickly. Please do not feel sad about this - it is how open source works. Also don't be angry if our high quality requirements cause in lots of changes until we finally push the button *MERGE*. Take it as a learning phase or teach us why your way is better :smile:

**Comment by rwaldron** [comment]
I'm undecided whether I want to make a change like this, but a few things to note: 

"Ready For Use" must mean...

- Code includes extensive _new_ unit tests
- PR message includes explicit "smoke tests/reality test" steps
- PR message includes clearly defined explanation of problem and solution


Probably more... I will add as I think of things.

**Comment by HipsterBrown** [comment]
> If you have created a useful feature
This is a fairly subjective statement, but I agree with @rwaldron in that "PR message includes clearly defined explanation of problem and solution" to clarify how it is useful to the PR author or other users.

> We do not like to have any barrier like intensive discussions. 
Discussions within open issues are a great place to expound upon ideas and discuss potential solutions, like within this issue now. We don't always do this for hotfixes or followup pull requests, but I trust it as a good practice for exchanging ideas without the pressure of merging because the work has already been done.

**Comment by Student007** [comment]
> "Ready For Use" must mean...

@rwaldron  you are right, it is required to define the requirements.
Maybe there should be an example. 
It should be good as "**If your PR match this requirements you can be sure to go back to your own stuff quickly**". 

High quality requirements are blocking people to contribute. **And not answering this is a sign "keep away"**. And that is not the vision of open source. So it is necessary to have usable rules for people who like to **make a gift without being bound to a discussion**.

Of cause people could hold their work back in their repo and wait for your visit and re-engineering.

**Comment by Student007** [comment]
@HipsterBrown this initiative is related to ideas are done. In general you are right but I know a lot of good programmers do not contribute to open source because of less time so they like to be sure they have no long therm discussion or what ever. You simple could take a look on statistics of new team members and how long they are doing. **In my case I would have done much more in the last few month but I hardly had to learn: Any contribution bound me to a long discussion in part two weeks for a quick fix**. And people told you they are angry about me do not accept I am not only a Student.

**Comment by HipsterBrown** [comment]
> I know a lot of good programmers do not contribute to open source because of less time so they like to be sure they have no long therm discussion

Building software as a group, whether it's a product for a company or an open source community, involves discussion. We want to make contributing this project as approachable as possible for new contributors, and making thorough issues are extremely helpful for this, like this [issue from the Hoodie project](https://github.com/hoodiehq/hoodie-account-server/issues/79) as an example.

I do believe in Work-In-Progress PRs that are opened before they are ready to be merged as a way to get early code review and encourage transparent collaboration. That usually comes after an issue has been opened and recognized, in my personal experience. 

> people told you they are angry about me do not accept I am not only a Student.

I don't know to what this is referring. I am giving my personal feedback on this issue.

**Comment by Student007** [comment]
> I do believe in Work-In-Progress PRs that are opened before they are ready to be merged as a way to get early code review and encourage transparent collaboration. That usually comes after an issue has been opened and recognized, in my personal experience. 

@HipsterBrown I totally agree. And to open a quick issue and linking a **Work-in-Progress-PR** is what I am looking for.
Most of the time I am finding things and write a solution for my current problem. Sometimes I notice it is my own issue while hacking and other times it is a working solution also for others. In the last cast I am creating a Work-in-Progress-PR (and for the future also an issue). I belief it is not a good style to blame with an issue all the time you find something your stumbled over. That way I provide a workaround or a suggestion. I think to call a **Work-in-Progress-PR** a **suggestion** is what I mean. Many times a programmer can explain thinks better that way.

For that I will add the following suggestion to the Agenda:
- Allowing "Work-in-Progress-PR"  bound to an issue for discussion of a provided solution/workaround
In general a workaround PR is better than no solution. Of cause it shouldn't close an issue until it is done in a better way.
- Adding  new the **Label** **[Work-in-Progress-PR]** and **[Workaround]**" to get a filter for those progresses (because of the risk the project becomes unclean). That labels should ensure a later quality review is focused.

**Comment by Frijol** [comment]
@Student007 this is clearly something you are passionate about. I'm glad that it's important to you, but I'm concerned (particularly from your comments [here](https://github.com/tessel/project/issues/147#issuecomment-208862782) that you are feeling offended when people disagree with you. Please excuse me if that's not the case, but if it is - I'd like to ask that you carefully check that your comments don't read as angry. It is difficult to have a useful conversation if you have to worry about someone expressing strong feelings about a stated opinion. I promise: no one is trying to specifically exclude you from contribution.

My personal thoughts on this issue:

* It is a good idea, even for small things, to make an issue before making a pull request.
* An issue is a good way to ensure the problem statement is clear: with an issue, you ask the question "what are we trying to solve?". With a pull request, the question should be "is this a good way to solve the problem?"
* I spend a fair amount of time asking contributors and community members to clarify what problem they are trying to solve - on both issues and PRs. Typically I have found PRs which are specifically tied to issues to be much clearer. This helps us be functional as an open and distributed team.
* By the time a PR is submitted, it is often harder to have the discussion about how a feature should best be implemented because someone has already put in the time. For example, I submitted an issue today about making the T2 CLI tell users it needed an update. I submitted this issue and immediately went to work on a PR. However, while I was working, LinusU gave me a suggestion which was better than what I was doing. I was glad I hadn't put any more time into my idea, because his was better and I would have been sad to have to re-implement after finishing.
* Creating a vague line of "useful feature" or similar in the rules makes it hard for the Steering Committee to do its job. It puts us in the uncomfortable position of sometimes telling people "we are rejecting your work because we find it not useful". A clear line, even if slightly pedantic at times, is a way to avoid this kind of issue.

**Comment by johnnyman727** [comment]
Hi everyone,

We discussed the merits of this suggestion at our Steering Committee Meeting yesterday. Ultimately, we all agreed that we'd like to *keep our contribution process as-is* (ie. creating Issues for discussion prior to a PR) for the following reasons:

1. We believe that creating an issue before opening a PR does not raise the barrier to contributing - it actually lowers it. New contributors can get involved without even understanding the codebase and more experienced contributors can provide them guidance on how to solve the particular problem at hand. Additionally, it reduces the chance that a new contributor will invest time in an unnecessary PR that will ultimately get closed without being merged and the frustration that *could* go along with that.

2. It is useful to have a distinction in the forum that a type of discussion takes place. If all discussion regarding the merit and strategy for solving a problem takes place in an Issue and all discussion regarding implementation takes place in a PR, it becomes much, much easier to search the discussion history at a later time. This consistency also lowers the barrier to entry for newcomers because it becomes easier to navigate the project and understand past decisions.

3. It makes our organization more efficient. Writing quality code and tests takes a lot of time. By ensuring we're only working on features/bug-fixes that are critical, we make more effective use of our limited resources.

Thanks for the discussion from everyone involved!
