### ISSUE TITLE
Agenda 04/12/15

### ISSUE THREAD

**Issue by johnnyman727** [tessel/project#147]
## Agenda
- [x] https://github.com/tessel/project/issues/146
- [x] How to triage issues moving forward (+ Windows 10)
- [x] Forums vs Github vs Slack ugh

**Comment by Frijol** [comment]
- [ ] Packs to propose to Seeed
- [ ] Policy on hackathon packs

**Comment by Frijol** [comment]
Moderator: @frijol
Note-taker: @rwaldron

**Comment by Student007** [comment]
- [ ] Not to comment: Same rules should be same for all...
- [ ] Because sometimes programmers can explain things  better with code, the new Label **[Work-in-Progress-PR]** and **[Workaround]** should be added and become part of the [guidlines](https://github.com/tessel/project/blob/master/CONTRIBUTING.md#pull-requests). Additional the corresponding requirements should be named. For instance: It needs a smoke test or "someone will tell you what parts should get a test".

Comment:
I belief a PR is also useful to discuss a solution. In my case I often figure out something and create a PR because I think it is useful for others. It is a kind of workaround and not to publish it would cause in double work or frustration of others which are not skilled enough at the point I was when working on it. Because the risk exists to get unclean code over time a filter label **[workaround]** is necessary for the case a **quickfix** is merged. This label has to be used with a corresponding **issue** which stays an **open issue** until that label is removed while a quality review is done.
I think this is a optimization of the current workflow. Without searching for special cases as existing examples I think you all know about things do not work well. And a review is not a good review in every case. So a frequently review of **[workaround]** would cause in removing those label and closing an issue or in an assignment to a someone is familiar with the problem. So finally this new format could be called **merge for temporary testdrive** and would increase productivity by reducing hurdle to contribute. Also a later assignment could be a recall of an inactive contributor as an expert (the nice way).

An example for things we do not have because a quickfix was not accepted: 
- [t2 list](https://github.com/tessel/t2-cli/pull/381) with colors (useful at events where much Tessel 2 are found by `t2 list` and the user cannot see which is the own one

A last word ... to the current guidelines:
I belief it is a tool to keep people like me away. Maybe this is the goal but if not it should get an improvement similar to the suggested idea. Btw: that way the current de facto style of development cycle is supported by a guideline - and further calls to follow the guideline become credible with leading by example.

**Comment by Frijol** [comment]
closed with https://github.com/tessel/project/commit/712748aa2044f705c0ede4aa00fe68264f0dce36
