### ISSUE TITLE
Support Week: Notes Collection 

### ISSUE THREAD

**Issue by HipsterBrown** [tessel/project#281]
As the Steering Committee tries a Support Week calendar, these are the follow-up notes from each Committee Member to track how each week goes.

**Comment by HipsterBrown** [comment]
# Tessel Support Week - 2017/04/18 to 2017/04/25

**Tuesday:**
    - nada

**Wednesday:**
    - #support channel question about network connection and posting data to remote service, ~45 minutes to solve/complete

**Thursday:**
    - "new" forum question posted on Tuesday, related to power management, answered and pointed to docs, 10 minutes

**Friday:**
    - forum post about WS2812, neopixels, with Tessel, answered with links to t2-firmware tracking issue and tessel-fadecandy package, 15 minutes
    - odd t2-cli issue about npm installing that looked unrelated to Tessel, 20 minutes

**Monday:**
    - #support channel question about network connection issues with Google WiFi, about 30 minutes

**Comment by rwaldron** [comment]
# Tessel Support Week - 2017/05/02 to 2017/05/08

Very quiet. 

- Node LTS is supported by t2-cli
- Working on openwrt-tessel, openwrt update

**Comment by tcr** [comment]
## 2017/04/25 to 2017/05/02

- Little activity during the weekdays
- Was OOO over the weekend at Disney, so slow to respond to new updates :(
- Supported some Reach inquiries

**Comment by Frijol** [comment]
Week of 5/3

* A few questions on forums, mostly follow-ups to existing conversations
* Probably spent a total of 30 minutes on support over the week
* Could have done more, but felt people were getting at least a minimum of help
* I think @rwaldron ended up helping people more than I did, partly because support requests were specific to tessel-av. @rwaldron curious to hear how you felt this week went, I wasn't very quick to respond to people so you might have jumped in more?

**Comment by Frijol** [comment]
Discussed and resolved in https://github.com/tessel/project/pull/288
