### ISSUE TITLE
Convert hardware modules to Kicad versions.

### ISSUE THREAD

**Issue by tcr** [tessel/project#40]
All of our modules are in Diptrace format, which is not a useful or open format.

https://tessel.io/opensource

There have been some attempts to convert these to Kicad, which should be completed / automated.

**Comment by tcr** [comment]
Recently we discussed improving the hardware modules by adding EEPROM labels to them. If it becomes simpler to release only the improved versions as Kicad versions, I think we should simply do that.

**Comment by ekolker** [comment]
I'm kind of torn here for a few reasons, but ultimately we should probably port everything over very soon in the name of consistent UX, decreased technical debt, and standardization. Here's what's in my head:

* We've long since switched to KiCad for our EDA tool of choice, as DipTrace is closed source and uses a freemium model (which goes against our ideology). Two-layer boards, however, are editable with the free version of DipTrace, which makes all the modules still accessible to the community. I think the only exception here might be GPRS (due to the drill count), but that's being discontinued anyway, so the point is mostly moot.
* Porting everything over ASAP is either really tedious and time consuming or wildly ineffective. Our options are either rebuild everything from the ground up (probably an average of ~3 hours per module to do it right) or use an import tool of some kind. Based on what I've seen, these tools do the equivalent of convert a PDF (generated from a LaTeX file) into an SVG where each letter is its own object: they split footprints and symbols into polygons and lines, lose metadata (datasheets, pin names, pin numbers), etc., which makes the output file useless if you ever want to manipulate it. I'm sure more work could be put into these tools, but I worry about [things](https://xkcd.com/1445/) [like](http://xkcd.com/1319/) [these](http://xkcd.com/1205/).
* As far as I know, very few people outside of Technical Machine have ever looked at any of the hardware design files. In other words, doing it right is time-expensive per unit of real benefit, and doing it quick and dirty just feels wrong.
* It would be really nice to only need one software package for hardware development on Tessel (I think I've used four at this point, but I'm *definitely* a special case).

Coming at it from a UX standpoint, then, it might make sense to convert everything over as a starting point and port things on an as-needed basis, making it very clear that we'd do this if asked. Or someone could bite the bullet and spend a few days on this.

As far as the I2C EEPROM is concerned... Yes, it would be nice for the system to be able to autodetect modules, this is the obvious way to do it, and putting a little storage on each module also happens to carry with it some clear secondary benefits.

Making these changes in DT would effectively just get us more technical debt, and doing it in KiCad would require that the modules be ported, not converted.

I personally don't want to do this right before I head to China, but at the same time, if it's going to happen, it should happen sooner rather than later so that the wave of modules that ship with the first T2s include the EEPROMs, which would give us a fighting chance of actually making this a usable standard moving forward. The costs here are monetary (probably adds ~$0.15 to the cost of the module), time, and that we may need new test rigs for the updated modules (more money and time).

Last but not least, while we're at it, we should put the I2C pull resistors on the modules (looking at you, RFID and Climate) so we can eventually remove them from T2 itself...

**Comment by Frijol** [comment]
We can revive this at some point in the future if it seems necessary, but for now it doesn't look like a good use of our time.
